# Generated by Django 5.0 on 2024-07-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newspost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='category_name',
        ),
    ]
