# Generated by Django 5.0 on 2024-07-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_newspost_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
