# Generated by Django 5.0 on 2024-07-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newspost_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
