# Generated by Django 5.0 on 2024-08-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_category_created_at_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='photo_editor',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
