# Generated by Django 5.0 on 2024-07-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('HOME', 'Home'), ('SEARCH_RESULT', 'Search_Result'), ('NEWS_POST', 'Newspost'), ('CATEGORY', 'Category'), ('TRENDINGTAGS', 'Trendingtags')], max_length=60)),
                ('section', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('video', models.URLField(blank=True)),
                ('height', models.CharField(max_length=20)),
                ('width', models.CharField(max_length=20)),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('HOME', 'Home'), ('SEARCH_RESULT', 'Search_Result'), ('NEWS_POST', 'Newspost'), ('CATEGORY', 'Category'), ('TRENDINGTAGS', 'Trendingtags')], max_length=60)),
                ('image', models.URLField()),
                ('link', models.URLField(blank=True)),
                ('height', models.CharField(max_length=20)),
                ('width', models.CharField(max_length=20)),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('column', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NavbarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrendingTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('is_latest', models.BooleanField(default=True)),
                ('newspost_tags', models.ManyToManyField(to='news.newspost')),
            ],
        ),
    ]
