# Generated by Django 5.0 on 2024-07-31 04:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0004_admodel_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_type', models.CharField(choices=[('NEWSPORTAL', 'Newsportal'), ('ADMIN_DASHBOARD', 'Admin_Dashboard')], max_length=15)),
                ('is_active', models.BooleanField()),
                ('height', models.CharField(max_length=20)),
                ('width', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
