# Generated by Django 5.0 on 2024-07-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0005_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='logo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
