# Generated by Django 5.0 on 2024-07-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EDITOR', 'Editor'), ('ADMIN', 'Admin'), ('SUPER_ADMIN', 'Super_Admin')], default='EDITOR', max_length=12),
        ),
    ]
